# Generated by Django 4.0.4 on 2022-06-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owned_by_users',
            field=models.ManyToManyField(to='api.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='owned_product',
            field=models.ManyToManyField(to='api.product'),
        ),
    ]
