# Generated by Django 4.0.4 on 2022-06-13 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_owned_by_users_user_owned_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owned_by_users',
        ),
        migrations.RemoveField(
            model_name='user',
            name='owned_product',
        ),
    ]
